<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Meatcorps.Game.ArcadeTemplate</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meatcorps.Engine.Assets.Packager" Version="0.1.*" />
    <PackageReference Include="Meatcorps.Engine.RayLib" Version="0.1.*" />
    <PackageReference Include="Meatcorps.Engine.RayLib.Assets" Version="0.1.*" />
    <PackageReference Include="Meatcorps.Engine.SDL" Version="0.1.*" />
    <PackageReference Include="Meatcorps.Engine.Session" Version="0.1.*" />
    <PackageReference Include="Meatcorps.Engine.Hardware.ArduinoController" Version="0.1.*" />
    <PackageReference Include="Meatcorps.Engine.AsciiScript" Version="0.1.*" />
    <PackageReference Include="Meatcorps.Engine.Arcade" Version="0.1.*" />
    <PackageReference Include="Meatcorps.Engine.Arcade.RayLib" Version="0.1.*" />
    <ProjectReference Include="..\Meatcorps.Engine.Arcade.RayLib\Meatcorps.Engine.Arcade.RayLib.csproj" />
    <ProjectReference Include="..\Meatcorps.Engine.Arcade\Meatcorps.Engine.Arcade.csproj" />
    <ProjectReference Include="..\Meatcorps.Engine.AsciiScript\Meatcorps.Engine.AsciiScript.csproj" />
    <ProjectReference Include="..\Meatcorps.Engine.Hardware.ArduinoController\Meatcorps.Engine.Hardware.ArduinoController.csproj" />
    <ProjectReference Include="..\Meatcorps.Engine.RayLib\Meatcorps.Engine.RayLib.csproj" />
    <ProjectReference Include="..\Meatcorps.Engine.Session\Meatcorps.Engine.Session.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Assets/**/*" />
  </ItemGroup>
  
  <ItemGroup>
    <Content Include="Assets/**/*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ClCompile Include="Assets\Shaders\bloom.fx" />
    <ClCompile Include="Assets\Shaders\bloom_composite.fx" />
    <ClCompile Include="Assets\Shaders\bloom_threshold.fx" />
    <ClCompile Include="Assets\Shaders\chromaticaberration.fx" />
    <ClCompile Include="Assets\Shaders\colorgrading.fx" />
    <ClCompile Include="Assets\Shaders\crt_newpixie.fx" />
    <ClCompile Include="Assets\Shaders\fixedpalette_tex.fx" />
    <ClCompile Include="Assets\Shaders\fixedpalette8.fx" />
    <ClCompile Include="Assets\Shaders\gaussian_blur.fx" />
    <ClCompile Include="Assets\Shaders\paletteswap.fx" />
    <ClCompile Include="Assets\Shaders\scanlines.fx" />
  </ItemGroup>

</Project>
