<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Meatcorps.Game.GameStarter</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="Meatcorps.Engine.Assets.Packager" Version="[0.1.0,)" />
    <ProjectReference Include="..\..\Meatcorps.Engine.Assets.Packager\Meatcorps.Engine.Assets.Packager.csproj" />
    <PackageReference Include="Meatcorps.Engine.RayLib" Version="[0.1.0,)" />
    <ProjectReference Include="..\..\Meatcorps.Engine.Assets\Meatcorps.Engine.Assets.csproj" />
    <PackageReference Include="Meatcorps.Engine.RayLib.Assets" Version="[0.1.0,)" />
    <ProjectReference Include="..\..\Meatcorps.Engine.RayLib.Assets\Meatcorps.Engine.RayLib.Assets.csproj" />
    <PackageReference Include="Meatcorps.Engine.RayLib" Version="[0.1.0,)" />
    <ProjectReference Include="..\..\Meatcorps.Engine.RayLib\Meatcorps.Engine.RayLib.csproj"/>
    <PackageReference Include="Meatcorps.Engine.SDL" Version="[0.1.0,)" />
    <ProjectReference Include="..\..\Meatcorps.Engine.SDL\Meatcorps.Engine.SDL.csproj" />
    <PackageReference Include="Meatcorps.Engine.Session" Version="[0.1.0,)" />
    <ProjectReference Include="..\..\Meatcorps.Engine.Session\Meatcorps.Engine.Session.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Assets/**/*"/>
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <Content Include="Assets/**/*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <PropertyGroup>
    <MSBuildWarningsAsMessages>High</MSBuildWarningsAsMessages>
    <ConsoleLoggerParameters>verbosity=detailed</ConsoleLoggerParameters>
  </PropertyGroup>

  <UsingTask TaskName="AssetPackageTask"
             AssemblyFile="$(ProjectDir)\bin\$(Configuration)\net8.0\Meatcorps.Engine.Assets.Packager.dll" />

  <Target Name="AssetPackageTask"
          AfterTargets="Build"
          Condition="'$(Configuration)' == 'Release'">

    <AssetPackageTask
            GameAssemblyPath="$(TargetPath)"
            ProjectDirectory="$(ProjectDir)"
            OutputPath="$(OutputPath)" />
  </Target>
</Project>
