<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RootNamespace>Meatcorps.Engine.RayLib.Examples</RootNamespace>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Meatcorps.Engine.AsciiScript\Meatcorps.Engine.AsciiScript.csproj" />
        <ProjectReference Include="..\Meatcorps.Engine.RayLib.ImGuiTools\Meatcorps.Engine.RayLib.ImGuiTools.csproj"/>
        <ProjectReference Include="..\Meatcorps.Engine.RayLib\Meatcorps.Engine.RayLib.csproj"/>
        <ProjectReference Include="..\Meatcorps.Engine.SDL\Meatcorps.Engine.SDL.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="HidSharp" Version="2.6.4"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="gamecontrollerdb.txt">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <None Update="PressStart2P-Regular.ttf">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Assets/**/*"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="Assets/**/*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
