namespace Meatcorps.Engine.Hardware.Controllers.Enums;

public enum ControllerInputEnum
{
    DPadUp,
    DPadDown,
    DPadLeft,
    DPadRight,
    AorCross,
    BorCircle,
    XorSquare,
    YorTriangle,
    LeftBumper,
    RightBumper,
    LeftTrigger,
    RightTrigger,
    Select,
    Start,
    Middle,
    LeftStick,
    LeftStickX,
    LeftStickY,
    RightStick,
    RightStickX,
    RightStickY,
    Button1,
    Button2,
    Button3,
    Button4,
    Button5,
    Button6,
    Button7,
    Button8,
    Button9,
    Button10,
}