namespace Meatcorps.Engine.Arcade.Leaderboard.GameEnums;

public enum GameSprites
{
    Explosion1,
    Explosion2,
    Explosion3,
    Explosion4,
    Explosion5,
    Explosion6,
    ExplosionAnimation,

    ArcadeButtonUp,
    ArcadeButtonDown,
    ArcadeButtonUpPlayerOne,
    ArcadeButtonDownPlayerOne,
    ArcadeButtonUpPlayerTwo,
    ArcadeButtonDownPlayerTwo,
    ArcadeButtonAnimation,
    ArcadeButtonPlayerOneAnimation,
    ArcadeButtonPlayerTwoAnimation,
    MiniArcadeButtonUp,
    MiniArcadeButtonDown,
    MiniArcadeButtonUpPlayerOne,
    MiniArcadeButtonDownPlayerOne,
    MiniArcadeButtonUpPlayerTwo,
    MiniArcadeButtonDownPlayerTwo,
    MiniArcadeButtonAnimation,
    MiniArcadeButtonPlayerOneAnimation,
    MiniArcadeButtonPlayerTwoAnimation,
    ArcadeStickCenter,
    ArcadeStickUp,
    ArcadeStickLeft,
    ArcadeStickRight,
    ArcadeStickDown,
    ArcadeStickArrowUp,
    ArcadeStickArrowLeft,
    ArcadeStickArrowDown,
    ArcadeStickArrowRight,
    ArcadeStickArrowUpLeft,
    ArcadeStickArrowDownLeft,
    ArcadeStickArrowDownRight,
    ArcadeStickArrowUpRight,
    ArcadeStickAnimationLeftRight,
    ArcadeStickAnimationTopDown,
    ArcadeStickAnimationRotate,
}