<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>Meatcorps.Engine.Arcade</PackageId>
        <Version>0.1.0</Version>
        <Authors>Dennis Steffen</Authors>
        <Company>Meatcorps</Company>
        <Product>Meatcorps Engine Arcade</Product>
        <Description>
            Meatcorps.Engine is a lightweight, code-first game framework built on top of Raylib. This is the arcade package
        </Description>
        <RepositoryUrl>https://github.com/meatcorps/Engine</RepositoryUrl>
        <PackageProjectUrl>https://www.meatcorps.nl/engine/</PackageProjectUrl>
        <PackageTags>game-engine;engine-core;gamedev;cross-platform;arcade;mqtt</PackageTags>
        <PackageLicenseFile>LICENSE</PackageLicenseFile>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Meatcorps.Engine.Core\Meatcorps.Engine.Core.csproj" />
        <PackageReference Include="Meatcorps.Engine.Core" Version="[0.1.0,)" />
        <ProjectReference Include="..\Meatcorps.Engine.MQTT\Meatcorps.Engine.MQTT.csproj" />
        <PackageReference Include="Meatcorps.Engine.MQTT" Version="[0.1.0,)" />
    </ItemGroup>

    <ItemGroup>
        <None Include="LICENSE" Pack="true" PackagePath=""/>
        <None Include="README.md" Pack="true" PackagePath=""/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="QRCoder" Version="1.6.0" />
    </ItemGroup>


</Project>
