<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="HidSharp" Version="2.6.4"/>
        <PackageReference Include="Raylib-cs" Version="7.0.1"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Meatcorps.Engine.Core\Meatcorps.Engine.Core.csproj"/>
        <ProjectReference Include="..\Meatcorps.Engine.Hardware.Controllers\Meatcorps.Engine.Hardware.Controllers.csproj"/>
        <ProjectReference Include="..\Meatcorps.Engine.Logging\Meatcorps.Engine.Logging.csproj"/>
    </ItemGroup>

</Project>
