<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Meatcorps.Engine.RayLib.ImGuiTools</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Meatcorps.Engine.RayLib\Meatcorps.Engine.RayLib.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
    </ItemGroup>

</Project>
