<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Meatcorps.Engine.Arcade\Meatcorps.Engine.Arcade.csproj" />
      <ProjectReference Include="..\Meatcorps.Engine.Logging\Meatcorps.Engine.Logging.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Data\" />
    </ItemGroup>

</Project>
