<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Meatcorps.Engine.Arcade.RayLib\Meatcorps.Engine.Arcade.RayLib.csproj" />
      <ProjectReference Include="..\Meatcorps.Engine.Arcade\Meatcorps.Engine.Arcade.csproj" />
      <ProjectReference Include="..\Meatcorps.Engine.AsciiScript\Meatcorps.Engine.AsciiScript.csproj" />
      <ProjectReference Include="..\Meatcorps.Engine.Boids\Meatcorps.Engine.Boids.csproj" />
      <ProjectReference Include="..\Meatcorps.Engine.Hardware.ArduinoController\Meatcorps.Engine.Hardware.ArduinoController.csproj" />
      <ProjectReference Include="..\Meatcorps.Engine.RayLib\Meatcorps.Engine.RayLib.csproj" />
      <ProjectReference Include="..\Meatcorps.Engine.Session\Meatcorps.Engine.Session.csproj" />
        <ProjectReference Include="..\Meatcorps.Engine.RayLib.Assets\Meatcorps.Engine.RayLib.Assets.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="Assets/**/*"/>
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
        <Content Include="Assets/**/*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <PropertyGroup>
        <MSBuildWarningsAsMessages>High</MSBuildWarningsAsMessages>
        <ConsoleLoggerParameters>verbosity=detailed</ConsoleLoggerParameters>
    </PropertyGroup>

    <UsingTask TaskName="AssetPackageTask"
               AssemblyFile="$(ProjectDir)\bin\$(Configuration)\net8.0\Meatcorps.Engine.Assets.Packager.dll" />

    <Target Name="AssetPackageTask"
            AfterTargets="Build"
            Condition="'$(Configuration)' == 'Release'">

        <AssetPackageTask
                GameAssemblyPath="$(TargetPath)"
                ProjectDirectory="$(ProjectDir)"
                OutputPath="$(OutputPath)" />
    </Target>

</Project>
