namespace Meatcorps.Game.HorrorJackpot.GameEnums;

public enum GameSprites
{
    Explosion1,
    Explosion2,
    Explosion3,
    Explosion4,
    Explosion5,
    Explosion6,
    ExplosionAnimation,

    ArcadeButtonUp,
    ArcadeButtonDown,
    ArcadeButtonUpPlayerOne,
    ArcadeButtonDownPlayerOne,
    ArcadeButtonUpPlayerTwo,
    ArcadeButtonDownPlayerTwo,
    ArcadeButtonAnimation,
    ArcadeButtonPlayerOneAnimation,
    ArcadeButtonPlayerTwoAnimation,
    MiniArcadeButtonUp,
    MiniArcadeButtonDown,
    MiniArcadeButtonUpPlayerOne,
    MiniArcadeButtonDownPlayerOne,
    MiniArcadeButtonUpPlayerTwo,
    MiniArcadeButtonDownPlayerTwo,
    MiniArcadeButtonAnimation,
    MiniArcadeButtonPlayerOneAnimation,
    MiniArcadeButtonPlayerTwoAnimation,
    ArcadeStickCenter,
    ArcadeStickUp,
    ArcadeStickLeft,
    ArcadeStickRight,
    ArcadeStickDown,
    ArcadeStickArrowUp,
    ArcadeStickArrowLeft,
    ArcadeStickArrowDown,
    ArcadeStickArrowRight,
    ArcadeStickArrowUpLeft,
    ArcadeStickArrowDownLeft,
    ArcadeStickArrowDownRight,
    ArcadeStickArrowUpRight,
    ArcadeStickAnimationLeftRight,
    ArcadeStickAnimationTopDown,
    ArcadeStickAnimationRotate,
    
    UIPanel,
    OverlayBg,
    SpeedSliderBg,
    SpeedSliderPointer,
    ResultPoint10,
    ResultPoint100,
    ResultReroll,
    ResultJackpot,
    ResultNothing,
    SkullTop1,
    SkullTop2,
    SkullTop3,
    SkullBottom1 ,
    SkullBottom2,
    SkullBottom3,
    SkullBottom4,
}